### ISSUE TITLE
Please allow substitution for the following proxy properties 

### ISSUE THREAD

**Issue by stroomdev10** [gchq/stroom-resources#81]
proxyRepositoryReaderConfig:
  readCron
  maxStreamSize
  maxFileScan
  maxAggregation

**Comment by at055612** [comment]
It is open for debate how much we want to use env vars to set values in the proxy yaml config rather than just setting them directly in the yml.  The env vars don't fit well with the nested structure of yaml so for some things we can't use env vars.  I should be able to add these ones but if you think you are already likely to be setting values in the yaml directly then there is probably no point.
